platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Bellerophon' do
  
	pod 'Alamofire'
	pod 'Bellerophon', :path => "../"
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
	    target.build_configurations.each do |config|
	        config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = '12.0'
	    end
	end
end
